## Arizona

In [97]:
qcounts_1count_info[qcounts_1count_info["StateAbbr_y"] == "AZ"]

,QuestionUno,count,Id_x,StateAbbr_x,PostText,CreatedUtc,Id_y,StateAbbr_y,CategoryUno,Category,...,TakenByAttorneyUno,TakenOnUtc,ClosedByAttorneyUno,ClosedOnUtc,LegalDeadline,date,month_year,lemma_tokens,lemma_back_to_text,PostTextTokens
2,EFA178CA-221F-4AEB-B1C8-96167E0EB2D4,1,10085,AZ,We intially rented on ### with a ### 1st of ea...,2018-07-04 00:02:42,197639,AZ,F16F6597-94E1-479C-8C06-2C95807E5412,Housing and Homelessness,...,NaN,NaN,NaN,2018-07-30 23:18:16,NaN,2018-07-04 00:02:02,2018-07-01,"[we, intially, rented, on, with, a, 1st, of, e...",we intially rented on with a 1st of each month...,"[intially, rented, 1st, month, landlord, asked..."
6,36309001-CD9E-42EB-B06C-E972ABBAE5DB,1,10084,AZ,My oldest daughters dad has been absent from ...,2018-07-02 20:26:25,197638,AZ,23F7D13F-7318-4331-9868-DC0B5ED176A4,Family and Children,...,NaN,NaN,NaN,2018-07-30 23:18:00,2018-07-23 00:00:00,2018-07-02 20:26:24,2018-07-01,"[my, oldest, daughters, dad, has, been, absent...",my oldest daughters dad has been absent from h...,"[oldest, daughters, dad, absent, life, financi..."
8,FC6DD642-41A2-46B5-A464-2B181D9E074E,1,9952,AZ,If I get an injunction against for harassment ...,2018-04-23 03:58:51,197538,AZ,D97CAE2D-5AC5-4792-837E-9390C8172CD8,Individual Rights,...,NaN,NaN,NaN,2018-05-31 20:55:51,NaN,2018-04-23 03:58:27,2018-04-01,"[if, i, get, an, injunction, against, for, har...",if i get an injunction against for harassment ...,"[injunction, harassment, iah, ordered, situati..."
9,1D0897C5-6BB5-434A-9A89-ABBFF9016538,1,9953,AZ,Is a voice recording enough to press charges o...,2018-04-23 04:03:51,197539,AZ,CD95B63C-0FA5-48D4-966F-4D5194495F72,Other,...,NaN,NaN,NaN,2018-05-31 20:54:40,NaN,2018-04-23 04:03:09,2018-04-01,"[is, a, voice, recording, enough, to, press, c...",is a voice recording enough to press charges o...,"[voice, recording, press, charges, situation, ..."
11,C9368D64-A92B-47B0-A9AF-13BAD4F035E4,1,9984,AZ,My husband has been cheating on me with a co-w...,2018-05-10 18:14:05,197566,AZ,23F7D13F-7318-4331-9868-DC0B5ED176A4,Family and Children,...,NaN,NaN,NaN,2018-07-02 22:29:52,NaN,2018-05-10 18:13:17,2018-05-01,"[my, husband, has, been, cheating, on, me, wit...",my husband has been cheating on me with a cowo...,"[husband, cheating, coworker, make, work, fixa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22242,C9F36DC4-BADA-439D-8398-2CD28920D64E,1,16262,AZ,My boyfriend and I got into an argument and w...,2021-08-25 02:48:10,33531,AZ,CD95B63C-0FA5-48D4-966F-4D5194495F72,Other,...,NaN,NaN,NaN,2021-09-27 06:47:04,2021-08-27 00:00:00,2021-08-25 02:47:43,2021-08-01,"[my, boyfriend, and, i, got, into, an, argumen...",my boyfriend and i got into an argument and we...,"[boyfriend, argument, collided, trash, throw, ..."
22247,50CF36C9-CB5E-487C-AC9F-B9F8307BAD65,1,16287,AZ,Never agreed to exempt in fact when I brought ...,2021-08-27 03:59:43,33539,AZ,7EED6701-A73D-4144-8B72-FE4204A1A9B4,"Work, Employment and Unemployment",...,NaN,NaN,NaN,2021-10-04 16:29:16,NaN,2021-08-27 03:59:34,2021-08-01,"[never, agreed, to, exempt, in, fact, when, i,...",never agreed to exempt in fact when i brought ...,"[agreed, exempt, fact, brought, attention, amo..."
22252,7592A2F7-55B9-457C-915B-AF62ADAF8383,1,16263,AZ,###'s medical marijuana act can protect medica...,2021-08-25 02:47:10,33532,AZ,7EED6701-A73D-4144-8B72-FE4204A1A9B4,"Work, Employment and Unemployment",...,NaN,NaN,NaN,2021-08-25 02:47:14,NaN,2021-08-25 02:46:36,2021-08-01,"[s, medical, marijuana, act, can, protect, med...",s medical marijuana act can protect medical ma...,"[medical, marijuana, protect, medical, marijua..."
22253,0B2E5B7F-158C-461D-AFF5-7894E02AEAC7,1,16264,AZ,###'s medical marijuana act can protect medica...,2021-08-25 02:53:10,33533,AZ,7EED6701-A73D-4144-8B72-FE4204A1A9B4,"Work, Employment and Unemployment",...,NaN,NaN,NaN,2021-09-27 06:48:03,NaN,2021-08-25 02:52:16,2021-08-01,"[s, medical, marijuana, act, can, protect, med...",s medical marijuana act can protect medical ma...,"[medical, marijuana, protect, medical, marijua..."
22255,5DDC673D-397E-443A-93B3-B9E6D02BAC93,1,16276,AZ,How can I win and not have to pay my speeding ...,2021-08-26 02:19:25,33537,AZ,CD95B63C-0FA5-48D4-966F-4D5194495F72,Other,...,NaN,NaN,NaN,2021-09-27 06:50:30,2021-09-15 00:00:00,2021-08-26 02:19:19,2021-08-01,"[how, can, i, win, and, not, have, to, pay, my...",how can i win and not have to pay my speeding ...,"[pay, speeding, ticket, bring, court, bumper, ..."

In [268]:
qcounts.head()

                                  count  count
0  6BA6DBC2-A629-49AA-B2A1-8A1C90202639    752
1  7DC5D01C-8997-4B9B-9E13-8DF46C4F5549    273
2  1A8A1A18-87BB-4EE8-88DB-5287EDB2FCC5    175
3  75441487-ED6A-45DC-97F4-A4CD0621F104    171
4  FA4E98D6-09C0-4ED0-96FB-406B53E1B222    159

In [279]:
#qcounts = qcounts.rename(columns={'count': 'QuestionUno', 'QuestionUno': 'count'})
#qcounts.columns = ['QuestionUno', 'count']
qcounts['answer_status'] = qcounts['count'].apply(lambda x: 'answered' if x > 1 else 'not answered')
#qcounts['answer_status'].value_count()
qcounts['answer_status'].value_counts()

answered        103825
not answered     56601
Name: answer_status, dtype: int64

In [128]:
qcounts_info = pd.merge(qcounts, qposts, on='QuestionUno')
qcounts_info = pd.merge(qcounts_info, qs, on='QuestionUno')
qcounts_info.head()

,QuestionUno,count,Id_x,StateAbbr_x,PostText,CreatedUtc,lemma_tokens,lemma_back_to_text,PostTextTokens,Id_y,...,Subcategory,AskedByClientUno,AskedOnUtc,TakenByAttorneyUno,TakenOnUtc,ClosedByAttorneyUno,ClosedOnUtc,LegalDeadline,date,month_year
0,6BA6DBC2-A629-49AA-B2A1-8A1C90202639,752,243032,NM,I am My ex-###yfriend is convinced I have a ba...,2020-07-20 17:13:19,"[i, am, my, exyfriend, is, convinced, i, have,...",i am my exyfriend is convinced i have a baby f...,"[exyfriend, convinced, baby, child, exists, to...",152937,...,Family/Divorce/Custody,7093C22B-E77D-4AF9-9A5C-460621BFA62B,2020-07-20 17:13:17,AA84A467-40B1-466C-AEB0-09E82CC54131,2020-07-20 17:21:45,AA84A467-40B1-466C-AEB0-09E82CC54131,2021-04-02 00:32:00,2020-07-28 00:00:00,2020-07-20 17:13:17,2020-07-01
1,6BA6DBC2-A629-49AA-B2A1-8A1C90202639,752,243033,NM,"Ms. Guillen,Thank you for trusting me with you...",2020-07-20 18:23:20,"[ms, guillenthank, you, for, trusting, me, wit...",ms guillenthank you for trusting me with your ...,"[guillenthank, trusting, question, recognize, ...",152937,...,Family/Divorce/Custody,7093C22B-E77D-4AF9-9A5C-460621BFA62B,2020-07-20 17:13:17,AA84A467-40B1-466C-AEB0-09E82CC54131,2020-07-20 17:21:45,AA84A467-40B1-466C-AEB0-09E82CC54131,2021-04-02 00:32:00,2020-07-28 00:00:00,2020-07-20 17:13:17,2020-07-01
2,6BA6DBC2-A629-49AA-B2A1-8A1C90202639,752,243034,NM,"No, I don't have any children period. And as f...",2020-07-20 21:02:22,"[no, i, dont, have, any, children, period, and...",no i dont have any children period and as far ...,"[dont, children, period, dna, test, exist, exw...",152937,...,Family/Divorce/Custody,7093C22B-E77D-4AF9-9A5C-460621BFA62B,2020-07-20 17:13:17,AA84A467-40B1-466C-AEB0-09E82CC54131,2020-07-20 17:21:45,AA84A467-40B1-466C-AEB0-09E82CC54131,2021-04-02 00:32:00,2020-07-28 00:00:00,2020-07-20 17:13:17,2020-07-01
3,6BA6DBC2-A629-49AA-B2A1-8A1C90202639,752,243035,NM,Will you also please forward those other email...,2020-07-20 21:04:22,"[will, you, also, please, forward, those, othe...",will you also please forward those other email...,"[forward, emails, beneficial, call, today, tom...",152937,...,Family/Divorce/Custody,7093C22B-E77D-4AF9-9A5C-460621BFA62B,2020-07-20 17:13:17,AA84A467-40B1-466C-AEB0-09E82CC54131,2020-07-20 17:21:45,AA84A467-40B1-466C-AEB0-09E82CC54131,2021-04-02 00:32:00,2020-07-28 00:00:00,2020-07-20 17:13:17,2020-07-01
4,6BA6DBC2-A629-49AA-B2A1-8A1C90202639,752,243036,NM,"Yes, I will be free anytime tomorrow my phone...",2020-07-21 01:12:25,"[yes, i, will, be, free, anytime, tomorrow, my...",yes i will be free anytime tomorrow my phone n...,"[free, anytime, tomorrow, phone, number, suppl...",152937,...,Family/Divorce/Custody,7093C22B-E77D-4AF9-9A5C-460621BFA62B,2020-07-20 17:13:17,AA84A467-40B1-466C-AEB0-09E82CC54131,2020-07-20 17:21:45,AA84A467-40B1-466C-AEB0-09E82CC54131,2021-04-02 00:32:00,2020-07-28 00:00:00,2020-07-20 17:13:17,2020-07-01

In [232]:
qcounts_info_az = qcounts_info[qcounts_info["StateAbbr_x"]=="AZ"]
qcounts_info_az = qcounts_info_az["QuestionUno"].value_counts().to_frame().reset_index()
qcounts_info_az = qcounts_info_az.rename(columns={'index': 'QuestionUno', 'QuestionUno': 'count'})
#qcounts_info_az

qcounts_info_az['answer_status'] = qcounts_info_az['count'].apply(lambda x: 'answered' if x > 1 else 'not answered')
qcounts_info_az['answer_status'].value_counts()
qcounts_info_az = pd.merge(qcounts_info_az, qs, on="QuestionUno")
#qcounts_info_az[['answer_status', 'Category']]

grouped_data = qcounts_info_az.groupby(['Category', 'answer_status']).size().reset_index(name='count')
grouped_data
#pd.set_option('display.max_colwidth', 50)
#grouped_data = qcounts_info_az.groupby(['Category', 'answer_status']).size().reset_index(name='count')
#qs.head()

                             Category answer_status  count
0        Consumer Financial Questions      answered     56
1        Consumer Financial Questions  not answered    195
2                           Education  not answered      2
3                 Family and Children      answered    774
4                 Family and Children  not answered    864
5               Health and Disability      answered      3
6               Health and Disability  not answered     38
7            Housing and Homelessness      answered    125
8            Housing and Homelessness  not answered    574
9                  Income Maintenance      answered      1
10                 Income Maintenance  not answered     36
11                  Individual Rights      answered     16
12                  Individual Rights  not answered    181
13                           Juvenile      answered      2
14                           Juvenile  not answered      4
15                              Other      answered    188
16                              Other  not answered    770
17  Work, Employment and Unemployment      answered     12
18  Work, Employment and Unemployment  not answered    152

In [234]:
grouped_data = qcounts_info_az.groupby(['Category', 'answer_status']).size().reset_index(name='count')
grouped_data

                             Category answer_status  count
0        Consumer Financial Questions      answered     56
1        Consumer Financial Questions  not answered    195
2                           Education  not answered      2
3                 Family and Children      answered    774
4                 Family and Children  not answered    864
5               Health and Disability      answered      3
6               Health and Disability  not answered     38
7            Housing and Homelessness      answered    125
8            Housing and Homelessness  not answered    574
9                  Income Maintenance      answered      1
10                 Income Maintenance  not answered     36
11                  Individual Rights      answered     16
12                  Individual Rights  not answered    181
13                           Juvenile      answered      2
14                           Juvenile  not answered      4
15                              Other      answered    188
16                              Other  not answered    770
17  Work, Employment and Unemployment      answered     12
18  Work, Employment and Unemployment  not answered    152

In [226]:
chart = alt.Chart(grouped_data).mark_bar().encode(
    x=alt.X('Category:N', title='Category'),
    y=alt.Y('count:Q', title='Count'),
    color=alt.Color('answer_status:N', title='Answer status')
)

facet_chart = chart.facet(column='Category:N')
facet_chart.show()

Displaying chart at http://localhost:55396/

KeyboardInterrupt:

In [161]:
qcounts_1count_info_short = qcounts_1count_info["StateAbbr_x"].value_counts().to_frame().reset_index().rename(columns={'index': 'StateAbbr', 'StateAbbr_x': 'count'})
qcounts_1count_info_short.head()

  StateAbbr  count
0        TX   8159
1        GA   5382
2        IN   5341
3        FL   3962
4        IL   3512

In [157]:
client_question = pd.merge(clients, qs, left_on='ClientUno', right_on='AskedByClientUno')
client_question = client_question.drop(columns=['AskedByClientUno'])
state_counts = pd.DataFrame(client_question['StateAbbr_x'].value_counts()).reset_index()
state_counts = state_counts.rename(columns={'index': 'StateAbbr', 'StateAbbr_x': 'count'})
state_counts.head()

  StateAbbr  count
0        TX  21225
1        IN  20760
2        FL  19864
3        SC  14192
4        IL  14074

In [167]:
qcoounts_ratio = pd.merge(qcounts_1count_info_short, state_counts, on='StateAbbr')
qcoounts_ratio['ratio'] = qcoounts_ratio['count_x']/qcoounts_ratio['count_y']

   StateAbbr  count_x  count_y     ratio
1         GA     5382     7605  0.707692
23        PA      472      693  0.681097
34        US      194      305  0.636066
6         AZ     2816     5453  0.516413
17        IA      941     1861  0.505642
14        CA     1150     2324  0.494836
25        VT      451     1074  0.419926
16        MD      997     2590  0.384942
0         TX     8159    21225  0.384405
29        AK      324      862  0.375870
35        KS      186      498  0.373494
31        AL      305      848  0.359670
8         OK     1938     5452  0.355466
5         MA     2916     8814  0.330837
37        MI      169      512  0.330078
28        CT      382     1170  0.326496
24        NH      467     1444  0.323407
10        NC     1886     6054  0.311530
26        MS      440     1501  0.293138
15        LA     1023     3824  0.267521
2         IN     5341    20760  0.257274
4         IL     3512    14074  0.249538
12        VA     1336     5466  0.244420
19        NE      767     3280  0.233841
22        HI      499     2136  0.233614
36        NJ      174      768  0.226562
33        NM      219      967  0.226474
13        NY     1246     5610  0.222103
20        ME      750     3407  0.220135
27        UT      395     1872  0.211004
21        AR      514     2436  0.211002
9         MO     1892     9054  0.208968
3         FL     3962    19864  0.199456
30        WY      316     1624  0.194581
7         TN     2126    11287  0.188358
18        WI      931     7466  0.124699
38        SD      126     1126  0.111901
11        SC     1585    14192  0.111683
32        WV      298     3342  0.089168

In [202]:
qcoounts_ratio.sort_values(by='ratio', ascending=False).to_csv('state_question_ratio.csv')

In [181]:
qs

,Id,StateAbbr,QuestionUno,CategoryUno,Category,SubcategoryUno,Subcategory,AskedByClientUno,AskedOnUtc,TakenByAttorneyUno,TakenOnUtc,ClosedByAttorneyUno,ClosedOnUtc,LegalDeadline,date,month_year
0,1,NC,BB53B2A4-7C1B-45C3-9693-62047889317D,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,9C35423C-914A-42BC-8EBC-A370E76E2178,2019-06-19 22:10:06,NaN,NaN,NaN,2019-08-13 15:09:06,2019-07-08 00:00:00,2019-06-19 22:10:06,6-2019
1,2,NC,0C49F841-2782-4313-961E-7882B96D0854,C8E1275A-6C42-42E4-9B7D-231BAC438FC9,Individual Rights,73A59926-BA0B-44EC-ABF3-F4C9181EEA83,Civil/Constitutional Rights,DF636AEE-7D08-4F90-9A5C-0A2A726C6B59,2019-06-19 23:34:36,NaN,NaN,NaN,2019-08-13 15:09:14,NaN,2019-06-19 23:34:36,6-2019
2,3,NC,BFC28E08-B6B1-4185-A91A-89DF90816BE4,C8E1275A-6C42-42E4-9B7D-231BAC438FC9,Individual Rights,73A59926-BA0B-44EC-ABF3-F4C9181EEA83,Civil/Constitutional Rights,DF636AEE-7D08-4F90-9A5C-0A2A726C6B59,2019-06-19 23:57:18,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 02:37:16,FA34142B-1575-4720-981C-2D28C3560137,2019-06-24 19:02:35,NaN,2019-06-19 23:57:18,6-2019
3,4,NC,45B24109-243A-489B-B0D2-2F36C2A369FE,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,C9C3FA40-0D60-49B9-97F1-63AFEFAFA484,2019-06-20 02:33:14,FA34142B-1575-4720-981C-2D28C3560137,2019-07-27 18:04:08,FA34142B-1575-4720-981C-2D28C3560137,2019-07-31 05:49:18,NaN,2019-06-20 02:33:14,6-2019
4,5,NC,C4707F71-FE4A-4154-8174-AF00BEE2B361,F6016FBD-9501-4448-BCD3-BBB0E834E33B,Consumer Financial Questions,73FE486E-2B51-456A-A6D9-78A7D05802AA,"Bankruptcy, Debts & Purchases",ED7DEA10-CDB7-4A05-891D-889D1EA710BE,2019-06-20 17:04:47,NaN,NaN,NaN,2019-08-13 15:09:20,NaN,2019-06-20 17:04:47,6-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202874,202875,NC,376FFF48-9068-4A8F-9316-2EB5A7E38001,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,E3257971-6837-4BAD-B00D-E4040F0C8B8A,Civil Procedure,82BDD11F-2168-4A44-BBFC-BA9B0543F289,2019-06-17 20:37:01,6E43EC98-8700-4439-98A9-52B663CCE348,2019-07-17 19:22:29,6E43EC98-8700-4439-98A9-52B663CCE348,2019-07-27 19:26:43,NaN,2019-06-17 20:37:01,6-2019
202875,202876,NC,98AA49B1-D423-4D12-9E70-A5BD6663DFE5,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,E3257971-6837-4BAD-B00D-E4040F0C8B8A,Civil Procedure,FF2959DA-CCA4-415A-BA9B-2D51F860C08D,2019-06-18 13:06:00,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 03:07:59,FA34142B-1575-4720-981C-2D28C3560137,2019-06-24 19:02:56,2019-06-18 00:00:00,2019-06-18 13:06:00,6-2019
202876,202877,NC,B80305AA-7509-436E-AFF8-6B33AC682730,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,E3257971-6837-4BAD-B00D-E4040F0C8B8A,Civil Procedure,35133217-A30F-42A7-8EB4-E15A03026247,2019-06-18 15:33:13,NaN,NaN,NaN,2019-08-13 15:10:18,2019-06-27 00:00:00,2019-06-18 15:33:13,6-2019
202877,202878,NC,DC374484-7C6E-44A3-9DB7-89B8868518F1,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,26D3CE4B-3540-477E-BA03-78EF65769A12,Other,A40F8543-330C-43A1-97AC-53C01FD4013E,2019-06-19 03:23:46,6E43EC98-8700-4439-98A9-52B663CCE348,2019-06-24 14:47:57,6E43EC98-8700-4439-98A9-52B663CCE348,2019-06-28 21:59:13,2019-07-01 00:00:00,2019-06-19 03:23:46,6-2019
202878,202879,NC,1F2F2FC1-4661-4A14-A7BE-43E883D1BD44,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,43228290-518B-48CA-8E39-D7A438CDCC2B,2019-06-19 20:34:08,NaN,NaN,NaN,2019-08-13 15:09:01,NaN,2019-06-19 20:34:08,6-2019